In [4]:
import numpy as np

In [10]:
simple_array = np.arange(10)
simple_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
float_array = np.arange(10, dtype=float)
float_array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
float_array.dtype

dtype('float64')

In [15]:
complex_array = float_array.astype(complex)
complex_array

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

In [28]:
# This is a list of integers
int_list = [
    912,  80, 611, 906, 302, 882, 907, 405, 784, 872, 919, 528, 865,
    569, 762, 318, 156, 761, 941,  10,  87, 137, 819, 553, 272, 325,
    888, 251,  28, 306, 538, 563,   2, 293, 226, 733, 760, 629,  64,
    446, 713, 542, 870, 767, 727, 406, 221, 554, 315, 222
]
int_list

[912,
 80,
 611,
 906,
 302,
 882,
 907,
 405,
 784,
 872,
 919,
 528,
 865,
 569,
 762,
 318,
 156,
 761,
 941,
 10,
 87,
 137,
 819,
 553,
 272,
 325,
 888,
 251,
 28,
 306,
 538,
 563,
 2,
 293,
 226,
 733,
 760,
 629,
 64,
 446,
 713,
 542,
 870,
 767,
 727,
 406,
 221,
 554,
 315,
 222]

In [ ]:
# Convert the list of integers to a NumPy array
int_array = np.array(int_list)
int_array

array([912,  80, 611, 906, 302, 882, 907, 405, 784, 872, 919, 528, 865,
       569, 762, 318, 156, 761, 941,  10,  87, 137, 819, 553, 272, 325,
       888, 251,  28, 306, 538, 563,   2, 293, 226, 733, 760, 629,  64,
       446, 713, 542, 870, 767, 727, 406, 221, 554, 315, 222])

In [27]:
int_array.dtype

dtype('int64')

In [30]:
scores_array = np.genfromtxt('../data/raw/scores.csv', delimiter=',', dtype=int)
scores_array

array([1297,  603, 1071,  539, 1222, 1424,  986,  397,  970, 1102,  499,
        533,  908,  559,  386, 1183,  595,   69, 1141,   76,  863, 1343,
        185,  895, 1312,   50,  918,  677,  394,  629, 1317,  944,  466,
        751, 1050,  301,  415,  784,   19, 1395, 1223,  979,  252, 1155,
         59,  107,  632,  995,  972,  867,  332,  751,  810,   50,   55,
        218,  997, 1085,  475, 1494])

In [32]:
scores_array.size

60

In [35]:
scores_array[2:5]

array([1071,  539, 1222])

In [37]:
scores_array ** 0

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
scores_array

array([1297,  603, 1071,  539, 1222, 1424,  986,  397,  970, 1102,  499,
        533,  908,  559,  386, 1183,  595,   69, 1141,   76,  863, 1343,
        185,  895, 1312,   50,  918,  677,  394,  629, 1317,  944,  466,
        751, 1050,  301,  415,  784,   19, 1395, 1223,  979,  252, 1155,
         59,  107,  632,  995,  972,  867,  332,  751,  810,   50,   55,
        218,  997, 1085,  475, 1494])