In [1]:
import numpy as np

In [3]:
# This is a list of integers
int_list = [
    912,  80, 611, 906, 302, 882, 907, 405, 784, 872, 919, 528, 865,
    569, 762, 318, 156, 761, 941,  10,  87, 137, 819, 553, 272, 325,
    888, 251,  28, 306, 538, 563,   2, 293, 226, 733, 760, 629,  64,
    446, 713, 542, 870, 767, 727, 406, 221, 554, 315, 222
]
int_list

[912,
 80,
 611,
 906,
 302,
 882,
 907,
 405,
 784,
 872,
 919,
 528,
 865,
 569,
 762,
 318,
 156,
 761,
 941,
 10,
 87,
 137,
 819,
 553,
 272,
 325,
 888,
 251,
 28,
 306,
 538,
 563,
 2,
 293,
 226,
 733,
 760,
 629,
 64,
 446,
 713,
 542,
 870,
 767,
 727,
 406,
 221,
 554,
 315,
 222]

In [ ]:
# Array of integers
int_array = np.array(int_list)
int_array

array([912,  80, 611, 906, 302, 882, 907, 405, 784, 872, 919, 528, 865,
       569, 762, 318, 156, 761, 941,  10,  87, 137, 819, 553, 272, 325,
       888, 251,  28, 306, 538, 563,   2, 293, 226, 733, 760, 629,  64,
       446, 713, 542, 870, 767, 727, 406, 221, 554, 315, 222])

In [7]:
int_array.shape

(50,)

In [11]:
# Reshape the array into a 10x5 (10 rows)x(5 columns) matrix
int_matrix = int_array.reshape(10, 5)
int_matrix

array([[912,  80, 611, 906, 302],
       [882, 907, 405, 784, 872],
       [919, 528, 865, 569, 762],
       [318, 156, 761, 941,  10],
       [ 87, 137, 819, 553, 272],
       [325, 888, 251,  28, 306],
       [538, 563,   2, 293, 226],
       [733, 760, 629,  64, 446],
       [713, 542, 870, 767, 727],
       [406, 221, 554, 315, 222]])

In [12]:
int_matrix.shape

(10, 5)

In [16]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [17]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [ ]:
# Stack the two arrays vertically
c = np.vstack((a, b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# Stack the two arrays horizontally
d = np.hstack((a, b))
d

array([1, 2, 3, 4, 5, 6])

In [20]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [21]:
b = np.array([[5, 6]])
b

array([[5, 6]])

In [ ]:
# Flatten the arrays and concatenate (axis=None)
flatten_array = np.concatenate((a, b), axis=None)
flatten_array

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Stack the arrays vertical (axis=0) (default)
vertical_array = np.concatenate((a, b), axis=0)
vertical_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
# Stack the arrays horizontal (axis=1)
horizontal_array = np.concatenate((a, b.T), axis=1)
horizontal_array

array([[1, 2, 5],
       [3, 4, 6]])